
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/JetBrains/CLion 2023.3.4/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        C:/Users/Acer/Desktop/PonulioCPP/cpp2024-Game/cmake-build-debug/CMakeFiles/3.27.8/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/JetBrains/CLion 2023.3.4/bin/mingw/bin/g++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        C:/Users/Acer/Desktop/PonulioCPP/cpp2024-Game/cmake-build-debug/CMakeFiles/3.27.8/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Acer/Desktop/PonulioCPP/cpp2024-Game/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-n04za4"
      binary: "C:/Users/Acer/Desktop/PonulioCPP/cpp2024-Game/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-n04za4"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Acer/Desktop/PonulioCPP/cpp2024-Game/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-n04za4'
        
        Run Build Command(s): "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~1/JETBRA~1/CLION2~1.4/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_b3005/fast
        C:\\Program Files (x86)\\GnuWin32\\bin  -f CMakeFiles\\cmTC_b3005.dir\\build.make CMakeFiles/cmTC_b3005.dir/build
        process_begin: CreateProcess(NULL, C:\\Program Files (x86)\\GnuWin32\\bin -f CMakeFiles\\cmTC_b3005.dir\\build.make CMakeFiles/cmTC_b3005.dir/build, ...) failed.
        make (e=2): The system cannot find the file specified.\x0d
        mingw32-make: *** [Makefile:126: cmTC_b3005/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: C:/Program Files/JetBrains/CLion 2023.3.4/bin/mingw/bin/gcc.exe"
    directories:
      source: "C:/Users/Acer/Desktop/PonulioCPP/cpp2024-Game/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-h4r4hs"
      binary: "C:/Users/Acer/Desktop/PonulioCPP/cpp2024-Game/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-h4r4hs"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Acer/Desktop/PonulioCPP/cpp2024-Game/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-h4r4hs'
        
        Run Build Command(s): "C:/Program Files/JetBrains/CLion 2023.3.4/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~1/JETBRA~1/CLION2~1.4/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_ebcfb/fast
        C:\\Program Files (x86)\\GnuWin32\\bin  -f CMakeFiles\\cmTC_ebcfb.dir\\build.make CMakeFiles/cmTC_ebcfb.dir/build
        process_begin: CreateProcess(NULL, C:\\Program Files (x86)\\GnuWin32\\bin -f CMakeFiles\\cmTC_ebcfb.dir\\build.make CMakeFiles/cmTC_ebcfb.dir/build, ...) failed.
        make (e=2): The system cannot find the file specified.\x0d
        mingw32-make: *** [Makefile:126: cmTC_ebcfb/fast] Error 2
        
      exitCode: 2
...
